# traefik-httproute-443-https.yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik-dashboard-route
  namespace: default # Traefik이 설치된 네임스페이스
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: default
    sectionName: websecure # HTTPS 리스너 사용
  hostnames:
  - "dashboard.hgcho.test"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /dashboard
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: api@internal    # Traefik 내부 API 서비스
      kind: TraefikService  # 핵심: 일반 Service가 아님
      group: traefik.io
---
